### ISSUE TITLE
Accept a directory of template files?

### ISSUE THREAD

**Issue by ben-eb** [chrisocast/grunt-faker#7]
Currently, grunt-faker doesn't accept minimatch patterns; i.e. if you wanted to compile a whole directory of templates you would have to specify another target for each one. Are you open to a pull request for this feature?

I'd imagine it would work like this:

``` js
faker: {
    templates: {
        jsonFormat: ['data-templates/**/*.json'],
        dest: 'data'
    }
}
```

**Comment by rrarunan** [comment]
I would love to have this feature too.
